#
# ArtifactHub: https://artifacthub.io/packages/helm/grafana/promtail
# GitHub: https://github.com/grafana/helm-charts/tree/main/charts/promtail
# Default Values: https://github.com/grafana/helm-charts/blob/main/charts/promtail/values.yaml
#
config:
    clients:
        - url: http://loki-gateway.loki/loki/api/v1/push

    snippets:
        extraScrapeConfigs: |
            # Add an additional scrape config for syslog
            - job_name: journal
              journal:
                path: /host/var/log/journal
                max_age: 36h
                labels:
                  job: systemd-journal
              relabel_configs:
                - source_labels:
                    - __journal__hostname
                  target_label: hostname
                # example label values: kubelet.service, containerd.service
                - source_labels:
                    - __journal__systemd_unit
                  target_label: unit
                # example label values: debug, notice, info, warning, error
                - source_labels:
                    - __journal_priority_keyword
                  target_label: level

extraVolumes:
    - name: journal
      hostPath:
          path: /var/log/journal

    - name: machine-id
      hostPath:
          path: /etc/machine-id

extraVolumeMounts:
    - name: journal
      mountPath: /host/var/log/journal
      readOnly: true

    - name: machine-id
      mountPath: /host/etc/machine-id
      readOnly: true

resources:
    limits:
        cpu: 150m
        memory: 192Mi
    requests:
        cpu: 100m
        memory: 128Mi

initContainers:
    - command:
          - sh
          - -c
          - sysctl -w fs.inotify.max_user_instances=1024
      image: busybox
      name: sysctl
