#
# ArtifactHub: https://artifacthub.io/packages/helm/argo/argocd-image-updater
# GitHub: https://github.com/argoproj/argo-helm/tree/main/charts/argocd-image-updater
# Default Values: https://github.com/argoproj/argo-helm/blob/main/charts/argocd-image-updater/values.yaml
#
nodeSelector:
    node-role: ops

resources:
    limits:
        cpu: 128m
        memory: 128Mi
    requests:
        cpu: 64m
        memory: 64Mi

config:
    # trace, debug, info, warn, error
    logLevel: info

    registries:
        - name: "Amazon ECR"
          api_url: "https://${AWS_ECR_REGISTRY_DOMAIN}"
          prefix: "${AWS_ECR_REGISTRY_DOMAIN}"
          credentials: ext:/scripts/aws-ecr-login.sh
          credsexpire: 11h59m
          default: true
          insecure: false
          ping: true

    authScripts:
      enabled: true
      scripts:
        aws-ecr-login.sh: |
          #!/bin/sh
          aws ecr --region "${AWS_PRIMARY_REGION}" get-authorization-token --output text --query 'authorizationData[].authorizationToken' | base64 -d
