name: Deploy Hosting Platform

on:
    push:
        branches:
            - main

    pull_request:
        branches:
            - main

env:
    REACTOR_ENVIRONMENT: prod
    REACTOR_NO_DOCKER: true
    REACTOR_SHELL_OUTPUT: true

    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_STATE_KMS_KEY_ID: ${{ secrets.AWS_STATE_KMS_KEY_ID }}
    AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

    ARGOCD_SERVER_SECRET: ${{ secrets.ARGOCD_SERVER_SECRET }}
    ARGOCD_ADMIN_PASSWORD: ${{ secrets.ARGOCD_ADMIN_PASSWORD }}

    GRAFANA_ADMIN_PASSWORD: ${{ secrets.GRAFANA_ADMIN_PASSWORD }}

    QDRANT_PASSWORD: ${{ secrets.QDRANT_PASSWORD }}

    CLOUDFLARE_DOMAIN: ${{ secrets.CLOUDFLARE_DOMAIN }}
    CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

    TF_CLI_ARGS: -no-color

jobs:
    provision:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Install Reactor
              run: |
                  git clone --depth 1 --branch cicd_fixes https://github.com/kube-reactor/core.git /tmp/reactor
                  /tmp/reactor/install.sh

            - name: Test Reactor Provisioning Plan
              if: github.event_name == 'pull_request'
              run: /tmp/reactor/bin/reactor up --plan

            - name: Provision Reactor Managed Systems
              if: github.event_name != 'pull_request'
              run: /tmp/reactor/bin/reactor up
